# Generated by Django 4.2.1 on 2023-05-19 17:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=22, unique=True, verbose_name='enrollment no')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=20, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('branch', models.CharField(blank=True, choices=[('BCA', 'BCA'), ('BCA DS', 'BCA DS')], max_length=20, verbose_name='Department')),
                ('mail_id', models.EmailField(blank=True, max_length=40, unique=True, verbose_name='mail id')),
                ('college_mail', models.EmailField(blank=True, max_length=40, unique=True, verbose_name='College mail')),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True, verbose_name='phone number')),
                ('password', models.CharField(max_length=15, verbose_name='password')),
                ('current_cgpa', models.FloatField(max_length=5, verbose_name='current cgpa')),
                ('tenth', models.CharField(blank=True, max_length=5, verbose_name='10th percentage')),
                ('twelfth', models.CharField(blank=True, max_length=5, verbose_name='12th percentage')),
                ('address_name', models.CharField(max_length=45, verbose_name='House name')),
                ('post_office', models.CharField(max_length=30, verbose_name='post office')),
                ('city', models.CharField(max_length=25, verbose_name='city')),
                ('district', models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Eranakulam', 'Eranakulam'), ('Kozhikode', 'Kozhikode'), ('Palakkad', 'Palakkad'), ('Kollam', 'Kollam'), ('Kannur', 'Kannur'), ('Kottayam', 'Kottayam'), ('Pathanamthitta', 'Pathanamthitta'), ('Kasaragod', 'Kasaragod'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Idukki', 'Idukki'), ('Thrissur', 'Thrissur'), ('Malappuram', 'Malappuram'), ('Wayanad', 'Wayanad')], max_length=25, verbose_name='district')),
                ('pincode', models.IntegerField(verbose_name='pincode')),
                ('father_name', models.CharField(max_length=20, verbose_name='father name')),
                ('mother_name', models.CharField(max_length=20, verbose_name='mother name')),
            ],
            options={
                'verbose_name_plural': 'Registration Table',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('experience', models.IntegerField(null=True)),
                ('Location', models.CharField(max_length=2000, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
