# Generated by Django 4.1.5 on 2023-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pincode',
            field=models.IntegerField(verbose_name='pincode'),
        ),
    ]
