# Generated by Django 4.1.5 on 2023-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_register_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='PG_cgpa',
        ),
        migrations.RemoveField(
            model_name='register',
            name='UG_cgpa',
        ),
        migrations.AddField(
            model_name='register',
            name='current_cgpa',
            field=models.FloatField(default=0, max_length=5, verbose_name='current cgpa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='branch',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BCA', 'BCA DS')], max_length=20, verbose_name='Department'),
        ),
    ]
