# Generated by Django 4.1.5 on 2023-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_register_branch_alter_register_college_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='tenth',
            field=models.CharField(blank=True, max_length=5, verbose_name='10th percentage'),
        ),
        migrations.AlterField(
            model_name='register',
            name='twelfth',
            field=models.CharField(blank=True, max_length=5, verbose_name='12th percentage'),
        ),
    ]
