# Generated by Django 4.1.5 on 2023-04-27 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_register_tenth_alter_register_twelfth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='date of birth'),
        ),
    ]
